import { Platform, StyleSheet } from "react-native";
import { statusBarHeight, width, Бирюзовый } from "./GLOBAL";

export const styles = StyleSheet.create({
    blurContainer: {
      borderWidth:1,
      borderColor:'#9999991A',
      paddingVertical: 20,
      paddingHorizontal: 24,
      textAlign: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      borderRadius: 20,
      gap:12
    },
    h1:{
        fontWeight:'400',
        lineHeight:33.6,
        fontSize:28,
        color:'#000000',
        fontFamily:'Poppins'
    },
    h2:{
        fontWeight:'400',
        lineHeight:28.8,
        fontSize:24,
        color:'#000000',
        fontFamily:'Poppins'
    },
    h3:{
        fontWeight:'600',
        lineHeight:28.8,
        fontSize:24,
        color:'#000000',
        fontFamily:'PoppinsSemiBold'
    },
    h4:{
        fontWeight:'600',
        lineHeight:19.2,
        fontSize:16,
        color:'#000000',
        fontFamily:'PoppinsSemiBold'
    },
    bodyText:{
        fontWeight:'400',
        lineHeight:16.8,
        fontSize:14,
        color:'#000000',
        fontFamily:'Poppins'
    },
    additional:{
        fontWeight:'400',
        lineHeight:19.2,
        fontSize:16,
        color:'#000000',
        fontFamily:'Poppins'
    },
    button:{
        fontWeight:'600',
        lineHeight:16.8,
        fontSize:14,
        color:'#000000',
        fontFamily:'PoppinsSemiBold'
    },
    smallText:{
        fontWeight:'400',
        lineHeight:14.4,
        fontSize:12,
        color:'#000000',
        fontFamily:'Poppins'
    },
    shadow:{
        shadowColor: "black",
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.25,
        shadowRadius: 2.22,
        elevation: 10,
    },
    blockProfile: {
        borderRadius:16, 
        flexDirection:'row', 
        alignItems:"center", 
        justifyContent:"space-between", 
        borderWidth:1, 
        borderColor:'#B5B5B555', 
        padding:8
    },
    tagContainer:{
        borderWidth:1, 
        borderColor:'#FFFFFF99', 
        borderRadius:16, 
        paddingVertical:3, 
        paddingHorizontal:7.5
    },
    blurNoWoman:{
        flex:1, 
        marginHorizontal:16, 
        borderWidth:1, 
        marginBottom:Platform.OS=='ios' ?103 :70, 
        borderRadius:16, 
        overflow:'hidden', 
        borderColor:'#B5B5B50', 
        alignItems:'center', 
        justifyContent:'center'
    },
    containerWomanBlock:{
        width:width, 
        height:'100%', 
        borderBottomLeftRadius:16, 
        borderBottomRightRadius:16, 
        position:"absolute", 
        justifyContent:"space-between", 
        top:0, 
        zIndex:2, 
        pointerEvents:'box-none'
    },
    blurLikeContainer:{
        width:"100%", 
        paddingHorizontal:16, 
        paddingBottom:16, 
        borderRadius:16,
        overflow:'hidden'
    },
    noLikeContainer:{
        borderRadius:180, 
        width:42, 
        aspectRatio:1, 
        backgroundColor:'#DFDFDF1A', 
        alignItems:"center", 
        justifyContent:"center"
    },
    imageContainer:{
        zIndex:9999, 
        borderBottomLeftRadius:20, 
        borderBottomRightRadius:20, 
        position:"relative"
    },
    blurSettingContainer:{
        flexDirection:"row", 
        padding:3, 
        overflow:"hidden", 
        borderRadius:16,
        alignItems:'center', 
        gap:4
    },
    tagContainerBlock:{
        flexDirection:"row", 
        flexWrap:"wrap", 
        paddingBottom:8, 
        alignItems:"center", 
        gap:8
    },
    alertContainer:{
        padding:8, 
        right:16, 
        top:53, 
        overflow:"hidden", 
        borderRadius:16, 
        backgroundColor:'#00000088', 
        gap:7, 
        position:'absolute',
        zIndex:999
    },
    backArrowContainer:{
        borderRadius:16,
        backgroundColor:'#00000070', 
        overflow:'hidden', 
        width:42, 
        height:42, 
        alignItems:"center", 
        justifyContent:"center"
    },
    womanInfoContainer:{
        flexDirection:'row', 
        alignItems:'flex-end', 
        paddingBottom:15, 
        justifyContent:'space-between'
    },
    eventPeopleImgContainer:{
        width:width-32, 
        gap:8, 
        marginBottom:30, 
        flexDirection:"row", 
        justifyContent:'space-between', 
        flexWrap:"wrap"
    },
    instaContainer:{
        position:'absolute', 
        top:8, 
        right:8, 
        backgroundColor:"#00000070", 
        paddingHorizontal:7, 
        paddingVertical:3, 
        borderRadius:16, 
        flexDirection:'row', 
        alignItems:"center",
        gap:4
    },
    tgContainer:{
        position:'absolute', 
        bottom:8, 
        left:8, 
        backgroundColor:"#00000070", 
        paddingHorizontal:11, 
        paddingVertical:4, 
        borderRadius:16, 
        flexDirection:'row', 
        alignItems:"center",
        gap:4
    },
    tagEventContainer:{
        paddingHorizontal:8,
        paddingVertical:10,
        alignItems:"center",
        justifyContent:'center',
        width:'33.3%',
        borderRadius:15
    },
    blurTagEventContainer:{
        borderRadius:16, 
        overflow:"hidden", 
        borderWidth:1, 
        borderColor:'#374A4E99', 
        flexDirection:"row", 
        justifyContent:'space-between', 
        alignItems:"center", 
        marginHorizontal:16, 
        marginBottom:16
    },
    addEventContainer:{
        position:"absolute", 
        alignItems:"center", 
        justifyContent:"center", 
        width:55, 
        height:55, 
        borderRadius:180, 
        backgroundColor:Бирюзовый, 
        bottom:Platform.OS=='ios'? 100 :75, 
        zIndex:999, 
        right:16
    },
    profileCameraContainer:{
        width:width*0.5, 
        marginBottom:8, 
        alignItems:"center", 
        justifyContent:"center", 
        borderRadius:16, 
        height:width*0.5, 
        backgroundColor:'#00000044'
    },
    buttonEvent:{
        backgroundColor:Бирюзовый, 
        width:55, 
        height:55, 
        position:'absolute', 
        bottom:16, 
        right:16, 
        zIndex:9, 
        borderRadius:90,
        justifyContent:"center",
        alignItems:"center"
    }
});